services:
  monitor:
    build: .
    container_name: monitor-app
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - mysql_default

networks:
  mysql_default:
    external: true
