services:
  monitor:
    build: .
    container_name: prometheus-scraper
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - mysql_mysql-net

networks:
  mysql_mysql-net:
    external: true
